apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-frontend-ingress
  namespace: default
  labels:
    app: backend
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: 51.250.92.91.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backendFrontend.serviceName }}
                port:
                  number: 80
